# jekyll serve --baseurl '' --host 0.0.0.0
baseurl: www.jolejo.de

collections:
  keramische_arbeiten:
    output: true
  content_posts:
    output: true
  news:
    output: true
  kurse:
    output: true
  press:
    output: true
  times:
    output: true

# # docker-compose up
# 
# # https://github.com/BretFisher/jekyll-serve
# # jekyll serve --baseurl ''
# # baseurl: www.jolejo.de
# baseurl: ''


## new release:
# git tag release-name
# git push --tags

# or
# tag=2025-05-10
# cd /Users/ogaida/jolejo; git tag $tag ; git push --tags; cd -
